# Generated by Django 5.2.17 on 2026-08-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade usada para consultar a previsão do tempo (obrigatório se is_outdoor).', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='is_outdoor',
            field=models.BooleanField(default=False, help_text='Marque se esta tarefa é uma atividade ao ar livre.'),
        ),
    ]
